---
version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-phpfpm
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./wordpress:/var/www/html
    ports:
      - 8080:80
    networks:
      - mynetwork
    depends_on:
      - wordpress
  db:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    networks:
      - mynetwork
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_USER=wordpress
      - PMA_PASSWORD=wordpress
    depends_on:
      - db
    networks:
      - mynetwork
  wordpress:
    image: wordpress:php7.4-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - mynetwork
networks:
  mynetwork: null
